image: "python:3.8"
#commands to run in the Docker container before starting each job.
before_script:
  - python --version
# different stages in the pipeline
stages:
  - Build
  - Test
include:
  template: Jobs/Code-Quality.gitlab-ci.yml
Build:
  stage: Build
  script: echo 'Pipeline started'
Code Quality:
  stage: Test
  artifacts:
    paths: [code-quality-report.json]
    
Test:
  stage: Test
  script:
    - python main_test.py dev
    - cd results
    - if grep -q "Failed" result.log; then  grep "Failed" result.log; exit 1;  else echo "OK";  grep "Passed" result.log; exit 0; fi