image: "python:3.8"
#commands to run in the Docker container before starting each job.
before_script:
  - python --version
# different stages in the pipeline
stages:
  - Build
  - Test
Build:
  stage: Build
  script: echo 'Pipeline started'
Test:
  stage: Test
  script:
    - python main_test.py dev
    - cd results
    - if grep -q "Failed" result.log; then  grep "Failed" result.log; exit 1;  else echo "OK";  grep "Passed" result.log; exit 0; fi