image: "python:3.8"
# different stages in the pipeline
stages:
  - build
  - test

include:
  - template: Code-Quality.gitlab-ci.yml

Build:
  stage: build
  script:
    - pip install elementpath
    - pip install loguru
    - python main.py

code_quality:
  stage: test
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo “$CI_SERVER_VERSION” | sed ‘s/^([0-9]).([0-9]).*/\1-\2-stable/’)
    - docker run
        --env SOURCE_CODE="$PWD"
        --env CODECLIMATE_VERSION=0.72.0
        --env TIMEOUT_SECONDS=900
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        192.168.0.1:5000/codequality:latest /code
    - pip install loguru
    - python main.py
  allow_failure: true
  artifacts:
    paths: [codequality.json, gl-code-quality-report.json]

Test:
  stage: test
  script:
    - python main_test.py dev
    - cd results
    - if grep -q "Failed" result.log; then  grep "Failed" result.log; exit 1;  else echo "OK";  grep "Passed" result.log; exit 0; fi