image: "python:3.7" 
#commands to run in the Docker container before starting each job.
before_script:
  - python --version
# different stages in the pipeline
stages:
  - Test
#defines the job in Static Analysis
pylint:
  stage: Test
  script:
    - cd C:/Users/Krystsina_Bahdanava/Work/apache-jmeter-5.3/bin
    - jmeter.bat -n -t AutomatedTestingHW2.jmx -l testresults.xml