image: "python:3.8"
#commands to run in the Docker container before starting each job.
before_script:
  - python --version
# different stages in the pipeline
stages:
  - Test
pylint:
  stage: Test
  script:
    - python main_test.py