image: "python:3.8"
#commands to run in the Docker container before starting each job.
before_script:
  - python --version
# different stages in the pipeline
stages:
  - build
  - test

include:
  - template: Code-Quality.gitlab-ci.yml

Build:
  stage: build
  script:
    - pip install elementpath
    - pip install loguru
    - python main.py

code_quality:
  stage: test
  script:
    - pip install loguru
    - python main.py
  allow_failure: true
  artifacts:
    paths: [codequality.json, gl-code-quality-report.json]

Test:
  stage: test
  script:
    - python main_test.py dev
    - cd results
    - if grep -q "Failed" result.log; then  grep "Failed" result.log; exit 1;  else echo "OK";  grep "Passed" result.log; exit 0; fi