image: "python:3.8"
# different stages in the pipeline
stages:
  - build
  - test
  - release

Build:
  stage: build
  script:
    - pip install elementpath
    - pip install loguru
    - python main.py

before_script:
  - python --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

test:pylint:
  stage: test
  image: python:3.8
  allow_failure: true
  script:
      - pip install pylint --quiet
      - pylint --ignored-classes=_socketobject *.py

Test:
  stage: test
  script:
    - python main_test.py dev
    - cd results
    - if grep -q "Failed" result.log; then  grep "Failed" result.log; exit 1;  else echo "OK";  grep "Passed" result.log; exit 0; fi


job:on-schedule:
  stage: release
  only:
    - schedules
  script:
    - echo "Release"
    - git add .
    - git commit -m 'Releasing branch'
    - git push origin release